services:

  mariadb:
    image: mariadb:11.8
    restart: unless-stopped
    container_name: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
